### ISSUE TITLE
Streams2 interface not splitting correctly?

### ISSUE THREAD

**Issue by myndzi** [max-mapper/binary-split#12]
I was just writing some one off scripts and used this to split stdin -- only to find that I was getting combined data from the source. I suspect this might be an artifact of using through2 and possibly not setting the readable portion of the stream in object mode to guarantee one push = one readable chunk.

`foo`:
```
/volume1/data/keke
/volume1/data/lar
/volume1/dufus
```

`test.js`:
```js
'use strict';

var split = require('binary-split'),
    fs = require('fs');

var stream = fs.createReadStream('./foo').pipe(split());

setTimeout(function () {
    console.log(stream.read().toString());
}, 500);
```

output:
```
admin@ds:~/merge-dirs$ node test
/volume1/data/keke/volume1/data/lar/volume1/dufus
```

```
admin@ds:~/merge-dirs$ node -v
v4.4.2
```

**Comment by myndzi** [comment]
Left some comments here, as well as pushed a branch up to a fork that includes tests that currently fail on node 7.4.0 as well, for your debugging convenience: https://github.com/maxogden/binary-split/issues/11

Sorry that I never saw any response to that issue.

**Comment by mourner** [comment]
Hey, sorry for a late response. Trying to understand the issue — is the current behavior something that's not expected and could be fixed on the `binary-split` side? My impression is that this is simply how object-mode streams work when converting them back to a string.

**Comment by myndzi** [comment]
What the heck, I never saw an alert for this response :( I also apologize for not responding quickly!

Object mode streams pass objects 1-to-1 -- if you write a buffer, you read a buffer. Non object-mode streams can combine buffers, so you might write two and read one. Since the point of the module is to split things specifically and precisely, it doesn't really do its job if you can read from the stream and have two lines smushed together. The code snippet demonstrates this behavior.

The fix is simply to make the readable stream an object mode stream.

**Comment by mourner** [comment]
@myndzi hmm, would a fix mean simply passing `{objectMode: true}` to `through` [here](https://github.com/maxogden/binary-split/blob/master/index.js#L10)?

**Comment by krisreeves-stripe** [comment]
I don't know -- I am not familiar with through/through2. It should be noted that you only need objectMode on the read side afaik.

**Comment by mourner** [comment]
Pushed a PR for this at #14
